### ISSUE TITLE
Make the first run as smooth as possible

### ISSUE THREAD

**Issue by robin850** [daplayer/daplayer#7]
The first use of the player should be as smooth as possible:
- [X] Make sure that the `~/.player` folder is created with the adequate files. (bc9afefcc26b26f2f472cfdf6c3da1fc4c44363c)
- [x] Try to guess the music folder by default (depending on the system and the locale). (https://github.com/daplayer/daplayer/commit/4df03da5fab9b4472850549ac0bfae873f9a6759)
- [x] Make sure to ask the user to pick a download location when they try to download a music/video for the first time. (﻿﻿https://github.com/daplayer/daplayer/commit/47fa002fb2dd55ffbe1fd7beb5b7010fd085c77d)
